const express = require("express") 

const adminRouter = require('./admin.routes')
const seriesRouter = require('./series.routs')
const productRouter = require('./product.routes')
const blogRouter = require('./blog.routes')
const schoolRouter = require('./school.routs')
const contactRouter = require('./contact.routes')
const libraryRouter = require('./library.routes')
const eventRouter = require('./event.routes')
const recipesRouter = require('./recipes.routes')
const zooRouter = require('./zoo.routes')
const groceryRouter = require('./grocery.routes')
const stationaryRouter = require('./stationary.route')
const animeRouter = require('./anime.routes')
const actorRouter = require('./actor.routes')
const mangaRouter = require('./manga.routes')
const treeRouter = require('./tree.routes')
const areaRouter = require('./area.routes')
const medicalRouter = require('./medical.routs')
const tvRouter = require('./tv.routes')
const seasonsRouter = require('./seasons.routes')
const petRouter = require('./pet.routes')
const carRouter = require('./car.routes')
const flowerRouter = require('./flower.routes')
const birdRouter = require('./bird.routes')
const animalRouter = require('./animal.routes')


const router = express()

router.use('/admin',adminRouter)
router.use('/series',seriesRouter)
router.use('/product',productRouter)
router.use('/blog',blogRouter)
router.use('/school',schoolRouter)
router.use('/contact',contactRouter)
router.use('/library',libraryRouter)
router.use('/event',eventRouter)
router.use('/recipes',recipesRouter)
router.use('/zoo',zooRouter)
router.use('/grocery',groceryRouter)
router.use('/stationary',stationaryRouter)
router.use('/anime',animeRouter)
router.use('/actor',actorRouter)
router.use('/manga',mangaRouter)
router.use('/tree',treeRouter)
router.use('/area',areaRouter)
router.use('/medical',medicalRouter)
router.use('/tv',tvRouter)
router.use('/seasons',seasonsRouter)
router.use('/pet',petRouter)
router.use('/car',carRouter)
router.use('/flower',flowerRouter)
router.use('/bird',birdRouter)
router.use('/animal',animalRouter)


module.exports = router